BIND_HOST: '0.0.0.0'
SECRET_KEY_BASE: YourSecretKeyBase
CORS_ORIGINS: '*'
HOST: example.com
PROTOCOL: https
DEVISE_SECRET: YourDeviseSecret
MAIL_SENDER: noreply@example.com
APP_NAME: Example App
DEVISE_PEPPER: YourDevisePepper
SENDGRID_USERNAME: YourSendgridUsername
SENDGRID_PASSWORD: YourSendgridPassword
MAIL_DOMAIN: example.com
BUGSNAG_API_KEY: YourApiKey
BUGSNAG_RELEASE_STAGE: development
